### ISSUE TITLE
提醒一下各位，vercel会封号

### ISSUE THREAD

**Issue by fgprodigal** [surgioproject/surgio#152]
我昨天被封号，发邮件询问被告知不让搭代理，我说这不是代理，他们说涉及到代理也不行

**Comment by Maasea** [comment]
+1，我被解封了，但是要求删除该项目。

**Comment by gqbre** [comment]
已被封.. 发邮件让他们把项目删了帮我恢复账户

**Comment by zt900403** [comment]
+1  被block了。然后发邮件删除项目。。

**Comment by gqbre** [comment]
部署到 Heroku，Quantumult X 关联配置文件报 kcferrordomaincfnetwork 错误 310，啊这..

**Comment by in-out** [comment]
可惜了 付费的话也会被封吗？有替代吗？

**Comment by fgprodigal** [comment]
> 可惜了 付费的话也会被封吗？有替代吗？

我自己在nas上搭了

**Comment by geekdada** [comment]
非常抱歉，Surgio 的一个非常不重要的功能导致了 Vercel 账号封锁。这里给出临时的解决方案。

写邮件给 support@vercel.com（如果你还没写的话）

标题：Account blocked
内容：My account was blocked because of using Surgio. I will remove it from my deployment once I get access to my account. Thank you.

在解封之后删除包含 Surgio 的项目，等待我给出后续的解决方案。

非常抱歉给大家带来麻烦。这里再次声明，Surgio 没有包含恶意代码。

**Comment by gqbre** [comment]
能重新部署到 Vercel 了吗现在？
